/**
 * Context provider do frontend; centraliza estado compartilhado e evita prop drilling entre telas e componentes.
 */
import React, { createContext, useContext, useEffect, useMemo, useState, ReactNode } from 'react';

export type AppLanguage = 'pt-BR' | 'en';
export type AppLocale = 'pt-BR' | 'en-US' | 'pt-PT' | 'de-DE' | 'en-IE';

type TranslationParams = Record<string, string | number>;

interface LanguageContextType {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => void;
  locale: AppLocale;
  setLocale: (locale: AppLocale) => void;
  t: (key: string, params?: TranslationParams) => string;
}

const STORAGE_KEY = 'app_language';
const LOCALE_STORAGE_KEY = 'app_locale';

const translations: Record<AppLanguage, Record<string, string>> = {
  'pt-BR': {
    'common.management': 'Gestão Financeira',
    'common.hello': 'Olá, {{name}}',
    'common.transactionsCount': '{{count}} transações',
    'common.settings': 'Configurações',
    'common.cancel': 'Cancelar',
    'common.save': 'Salvar',
    'common.change': 'Alterar',
    'common.confirm': 'Confirmar',
    'common.active': 'Ativo',
    'common.activate': 'Ativar',
    'common.deactivate': 'Desativar',
    'common.close': 'Fechar',
    'common.user': 'Usuário',
    'common.more': 'Mais',
    'common.search': 'Buscar',
    'common.all': 'Todas',
    'common.income': 'Receitas',
    'common.expense': 'Despesas',
    'common.deleting': 'Excluindo',
    'common.loading': 'Carregando...',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.create': 'Criar',
    'common.deposit': 'Depositar',
    'common.progress': 'Progresso',
    'common.pending': 'Pendente',
    'common.paid': 'Pago',
    'common.overdue': 'Vencido',
    'common.records': '{{count}} registros',
    'common.entries': '{{count}} entradas',
    'common.noData': 'Nenhum dado disponível',

    'sidebar.dashboard': 'Dashboard',
    'sidebar.accounts': 'Contas',
    'sidebar.budgets': 'Orçamentos',
    'sidebar.goals': 'Metas',
    'sidebar.invoices': 'Faturas',
    'sidebar.timeline': 'Linha do Tempo',
    'sidebar.fixed': 'Recorrentes',
    'sidebar.history': 'Extrato',
    'sidebar.feedbacks': 'Feedbacks',
    'sidebar.admin': 'Painel Admin',
    'sidebar.settings': 'Configurações',
    'sidebar.mobileDownload': 'Baixar Versão Mobile',
    'sidebar.leaveFeedback': 'Deixar Feedback',
    'sidebar.mobileSettings': 'Ajustes',

    'header.dashboard': 'Dashboard',
    'header.accounts': 'Contas & Cartões',
    'header.timeline': 'Linha do Tempo',
    'header.goals': 'Metas & Sonhos',
    'header.budgets': 'Orçamentos',
    'header.invoices': 'Faturas',
    'header.fixed': 'Recorrentes',
    'header.feedbacks': 'Feedbacks (Admin)',
    'header.admin': 'Painel Admin',
    'header.history': 'Extrato',
    'header.settings': 'Configurações',
    'header.newTransaction': 'Novo Lançamento',
    'header.newTransactionMobile': '+ Lançamento',
    'header.newTransactionTitle': 'Novo Lançamento',

    'dashboard.available': 'Disponível (Mês)',
    'dashboard.currentBalance': 'Saldo Atual',
    'dashboard.cardInvoice': 'Fatura Cartão',
    'dashboard.monthIncome': 'Entradas (Mês)',
    'dashboard.monthExpense': 'Saídas (Mês)',
    'dashboard.smartInsights': 'Insights Inteligentes',
    'dashboard.analyzeMonth': 'Analisar meu Mês',
    'dashboard.updateTips': 'Atualizar Dicas',
    'dashboard.insightsPrompt': 'Peça para a nossa IA analisar seus gastos desse mês e te dar dicas personalizadas.',
    'dashboard.monthlyPerformance': 'Performance Mensal',
    'dashboard.cashFlow': 'Fluxo consolidado de caixa',
    'dashboard.welcome': 'Bem-vindo(a) ao Finanza!',
    'dashboard.welcomeDesc': 'Para começar a organizar suas finanças, primeiro registre onde seu dinheiro fica guardado.',
    'dashboard.addAccount': 'Acesse "Contas & Cartões" no menu',
    'dashboard.noEntries': 'Nenhum lançamento neste mês',
    'dashboard.noEntriesDesc': 'Que tal começar a organizar suas finanças registrando sua primeira movimentação?',
    'dashboard.startEntry': 'Comece pelo botão "Novo Lançamento"',
    'dashboard.fixedPending': 'Fixos Pendentes',
    'dashboard.allPaid': 'Tudo em dia!',
    'dashboard.noPendingFixed': 'Nenhuma conta fixa pendente.',
    'dashboard.topExpenses': 'Top Gastos',
    'dashboard.insufficientData': 'Sem dados suficientes.',
    'dashboard.compromise': 'Comprometimento',
    'dashboard.fixedRatioDesc': 'Da sua renda mensal está comprometida com fixos.',
    'dashboard.fixedCost': 'Custos Fixos',
    'dashboard.free': 'Livre',
    'dashboard.fixedLabel': 'Fixo: {{value}}',
    'dashboard.ruleTitle': 'Regra 50/30/20',
    'dashboard.financialHealth': 'Saúde Financeira',
    'dashboard.needs': 'Necessidades (50%)',
    'dashboard.wants': 'Desejos (30%)',
    'dashboard.savings': 'Objetivos (20%)',
    'dashboard.other': 'Outros',
    'dashboard.uncategorized': 'Categorias não classificadas na regra',
    'dashboard.resourceAllocation': 'Alocação de Recursos',
    'dashboard.expenses': 'Despesas',
    'dashboard.noCategoryData': 'Sem dados de categorização',
    'dashboard.pendingInvoices': 'Faturas Pendentes',
    'dashboard.creditCard': 'Cartão de Crédito',
    'dashboard.due': 'Vence {{date}}',
    'dashboard.total': 'Total: {{value}}',
    'dashboard.paid': 'Pago: {{value}}',
    'dashboard.suggestion': 'Sugestão: {{value}}',
    'dashboard.incomes': 'Receitas',
    'dashboard.revenues': 'Receitas',
    'dashboard.needsTooltip': 'Gastos essenciais como Aluguel, Alimentação, Luz, Água e Saúde. Limite sugerido: 50%.',
    'dashboard.wantsTooltip': 'Lazer, Hobbies, Assinaturas, Restaurantes e Compras não-essenciais. Limite sugerido: 30%.',
    'dashboard.savingsTooltip': 'Investimentos, Reserva de Emergência, Aposentadoria e Quitação de Dívidas. Mínimo sugerido: 20%.',
    'dashboard.uncategorizedTooltip': 'Gastos em categorias não classificadas na regra 50/30/20 (categorias personalizadas).',

    'history.title': 'Extrato Detalhado',
    'history.subtitle': 'Movimentações',
    'history.noTransactions': 'Nenhuma movimentação',
    'history.noTransactionsDesc': 'As transações aparecerão aqui conforme você adicioná-las.',
    'history.loadError': 'Erro ao carregar o extrato',
    'history.loadErrorDesc': 'Não foi possível carregar suas transações agora. Tente novamente em instantes.',
    'history.filterAll': 'Todas',
    'history.filterIncome': 'Receitas',
    'history.filterExpense': 'Despesas',
    'history.other': 'Outros',
    'history.search': 'Buscar transações...',
    'history.consolidated': 'Extrato Consolidado',
    'history.smartFilters': 'Filtros Inteligentes',
    'history.columnItem': 'Item',
    'history.columnCategory': 'Categoria',
    'history.columnDate': 'Data',
    'history.columnAmount': 'Valor',
    'history.columnManage': 'Gerenciar',

    'timeline.title': 'Caminho Financeiro',
    'timeline.subtitle': 'Jornada Temporal',
    'timeline.desc': 'Sua história detalhada dia após dia',
    'timeline.noData': 'Nenhuma transação encontrada',
    'timeline.loading': 'Carregando linha do tempo...',
    'timeline.loadError': 'Erro ao carregar a linha do tempo',
    'timeline.loadErrorDesc': 'Não foi possível carregar suas transações agora. Tente novamente em instantes.',

    'goals.title': 'Metas & Sonhos',
    'goals.newGoal': 'Nova Meta',
    'goals.editGoal': 'Editar Meta',
    'goals.goalTitle': 'Título',
    'goals.targetAmount': 'Valor Alvo',
    'goals.currentAmount': 'Valor Atual',
    'goals.deadline': 'Prazo',
    'goals.progress': 'Progresso: {{percent}}%',
    'goals.remaining': 'Faltam {{value}}',
    'goals.noGoals': 'Crie sua primeira meta',
    'goals.noGoalsDesc': 'Estabeleça objetivos financeiros para manter o foco e acompanhar seu progresso.',
    'goals.deposit': 'Depositar',
    'goals.depositAmount': 'Valor do depósito',
    'goals.depositSuccess': 'Depósito realizado com sucesso!',
    'goals.depositError': 'Erro ao realizar depósito',
    'goals.saved': 'Salvo!',
    'goals.notFound': 'Meta não encontrada',
    'goals.deleteConfirm': 'Tem certeza que deseja excluir esta meta?',
    'goals.deleteSuccess': 'Meta excluída com sucesso!',
    'goals.deleteError': 'Erro ao excluir meta',
    'goals.saving': 'Salvando...',
    'goals.saveSuccess': 'Meta salva com sucesso!',
    'goals.saveError': 'Erro ao salvar meta',
    'goals.income': 'Renda',
    'goals.amount': 'Valor',
    'goals.daysLeft': '{{days}} dias restantes',

    'budgets.title': 'Orçamentos',
    'budgets.planning': 'Planejamento',
    'budgets.noBudgets': 'Nenhum orçamento criado',
    'budgets.noBudgetsDesc': 'Crie orçamentos por categoria para controlar seus gastos.',
    'budgets.newBudget': 'Novo Orçamento',
    'budgets.editBudget': 'Editar Orçamento',
    'budgets.category': 'Categoria',
    'budgets.amount': 'Valor Limite',
    'budgets.spent': 'Gasto',
    'budgets.remaining': 'Restante',
    'budgets.overBudget': 'Acima do Orçamento!',
    'budgets.withinBudget': 'Dentro do Orçamento',
    'budgets.freeLimit': 'Plano Free permite 3 orçamentos. Faça upgrade para Premium para criar mais orçamentos.',
    'budgets.freeLimitTitle': 'Limite do plano Free',
    'budgets.createMore': 'Upgrade para criar mais',
    'budgets.viewPremium': 'Ver Premium',
    'budgets.loading': 'Carregando orçamentos...',
    'budgets.loadError': 'Erro ao carregar orçamentos',
    'budgets.fillAllFields': 'Preencha todos os campos',
    'budgets.invalidAmount': 'Valor inválido',
    'budgets.updateSuccess': 'Orçamento atualizado com sucesso!',
    'budgets.saving': 'Salvando...',
    'budgets.saveSuccess': 'Orçamento salvo com sucesso!',
    'budgets.saveError': 'Erro ao salvar orçamento',
    'budgets.deleteSuccess': 'Orçamento excluído com sucesso!',
    'budgets.deleteError': 'Erro ao excluir orçamento',
    'budgets.deleteConfirm': 'Tem certeza que deseja excluir este orçamento?',
    'budgets.deleteConfirmWithCategory': 'Tem certeza que deseja excluir o orçamento de {{category}}?',
    'budgets.deleteBudget': 'Excluir Orçamento',
    'budgets.readOnlyMode': 'Recurso em modo somente leitura',
    'budgets.used': 'utilizado',
    'budgets.planYourExpenses': 'Planeje seus gastos',
    'budgets.selectCategory': 'Selecione uma categoria...',
    'budgets.incomeGroup': 'Entradas (Rendas)',
    'budgets.needsGroup': 'Necessidades (Essencial)',
    'budgets.wantsGroup': 'Desejos (Estilo de Vida)',
    'budgets.goalsGroup': 'Objetivos (Quitação e Reserva)',
    'budgets.desiredMonthlyLimit': 'Limite Mensal Desejado',
    'budgets.updateBudget': 'Atualizar Orçamento',
    'budgets.saveBudget': 'Salvar Orçamento',

    'recurring.title': 'Recorrentes',
    'recurring.subtitle': 'Lançamentos fixos mensais',
    'recurring.noRecurring': 'Nenhum lançamento recorrente',
    'recurring.noRecurringDesc': 'Configure contas fixas como aluguel, assinaturas e salários.',
    'recurring.newRecurring': 'Novo Recorrente',
    'recurring.editRecurring': 'Editar Recorrente',
    'recurring.description': 'Descrição',
    'recurring.amount': 'Valor',
    'recurring.type': 'Tipo',
    'recurring.dueDay': 'Dia de Vencimento',
    'recurring.category': 'Categoria',
    'recurring.account': 'Conta',
    'recurring.monthlyWeight': 'Peso Mensal',
    'recurring.totalFixed': 'Total de Fixos',
    'recurring.missingTotal': 'Total Pendente',
    'recurring.loadError': 'Erro ao carregar recorrentes',
    'recurring.saveSuccess': 'Recorrente salvo com sucesso!',
    'recurring.saveError': 'Erro ao salvar recorrente',
    'recurring.deleteSuccess': 'Recorrente excluído com sucesso!',
    'recurring.deleteError': 'Erro ao excluir recorrente',
    'recurring.deleteConfirm': 'Tem certeza que deseja excluir este recorrente?',
    'recurring.typeIncome': 'Entrada',
    'recurring.typeExpense': 'Saída',
    'recurring.saving': 'Salvando...',

    'settings.title': 'Configurações',
    'settings.subtitle': 'Gerencie seus dados pessoais e plano.',
    'settings.preferences': 'Preferências',
    'settings.preferences.helper': 'A moeda define o símbolo/valor. O idioma define os textos e o formato de datas e números.',
    'settings.currency': 'Moeda',
    'settings.language': 'Idioma',
    'settings.language.pt': 'Português (Brasil)',
    'settings.language.en': 'English (US)',
    'settings.locale': 'Localidade',
    'settings.locale.ptBR': 'Português (Brasil)',
    'settings.locale.enUS': 'English (US)',
    'settings.locale.ptPT': 'Português (Portugal)',
    'settings.locale.deDE': 'Deutsch (Deutschland)',
    'settings.locale.enIE': 'English (Ireland)',
    'settings.preferencesSaved': 'Preferências salvas com sucesso!',
    'settings.preferencesError': 'Erro ao salvar preferências',
    'settings.displayName': 'Nome de Exibição',
    'settings.namePlaceholder': 'Seu nome',
    'settings.email': 'E-mail',
    'settings.newEmail': 'Novo e-mail',
    'settings.confirmPasswordCurrent': 'Confirme sua senha',
    'settings.password': 'Senha',
    'settings.passwordButton': 'Alterar senha de acesso',
    'settings.currentPassword': 'Senha atual',
    'settings.newPassword': 'Nova senha (mín. 8 caracteres, letras e números)',
    'settings.confirmPassword': 'Confirmar nova senha',
    'settings.passwordMismatch': 'As senhas não coincidem',
    'settings.plan': 'Plano Atual',
    'settings.plan.free': 'Gratuito',
    'settings.plan.premium': 'Premium',
    'settings.plan.freeDesc': '1 pedido de IA/dia, 1 conta, 1 cartão, 3 orçamentos, 3 metas',
    'settings.plan.premiumDesc': 'IA ilimitada, contas e orçamentos sem limite',
    'settings.confirmEmailChange': 'Confirmar Alteração',
    'settings.changePassword': 'Alterar Senha',
    'settings.success.name': 'Nome atualizado com sucesso!',
    'settings.success.password': 'Senha alterada com sucesso!',
    'settings.success.email': 'E-mail alterado! Verifique seu novo endereço.',
    'settings.error.name': 'Erro ao alterar nome',
    'settings.error.password': 'Erro ao alterar senha',
    'settings.error.email': 'Erro ao alterar e-mail',
    'settings.error.passwordLength': 'A nova senha deve ter pelo menos 8 caracteres, incluindo letras e números',
    'settings.upgradePremium': 'Fazer Upgrade para Premium',
    'settings.deleteAccount': 'Excluir Conta',
    'settings.deleteAccountDesc': 'Ação irreversível — todos os dados serão perdidos',
    'settings.delete': 'Excluir',
    'settings.deleteWarning': '⚠️ Esta ação é irreversível!',
    'settings.deleteItems': 'Todas as suas transações serão excluídas\nContas bancárias, cartões e saldos serão apagados\nMetas, orçamentos e categorias personalizados serão perdidos\nSeu plano premium será cancelado sem reembolso\nNão será possível recuperar os dados depois',
    'settings.deletePasswordPlaceholder': 'Digite sua senha para confirmar',
    'settings.deleteConfirmLabel': 'Digite EXCLUIR para confirmar',
    'settings.deleteConfirmPlaceholder': 'EXCLUIR',
    'settings.deletePermanently': 'Excluir Permanentemente',
    'settings.deleteError': 'Erro ao excluir conta',
    'settings.maintenance': 'Manutenção & Dados',
    'settings.exportTransactions': 'Exportar Transações',
    'settings.exportCSV': 'Backup em CSV',
    'settings.exportPersonalData': 'Exportar Dados Pessoais',
    'settings.exportLGPD': 'LGPD — Portabilidade completa (JSON)',
    'settings.exportSuccess': 'Dados pessoais exportados com sucesso (LGPD — portabilidade)',
    'settings.exportError': 'Erro ao exportar dados pessoais',
    'settings.exportPersonalDataSuccess': 'Dados pessoais exportados com sucesso (LGPD — portabilidade)',
    'settings.logout': 'Encerrar Sessão',
  },

  en: {
    'common.records': '{{count}} records',
    'common.management': 'Financial Management',
    'common.hello': 'Hello, {{name}}',
    'common.transactionsCount': '{{count}} transactions',
    'common.settings': 'Settings',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.change': 'Change',
    'common.confirm': 'Confirm',
    'common.active': 'Active',
    'common.activate': 'Activate',
    'common.deactivate': 'Deactivate',
    'common.close': 'Close',
    'common.user': 'User',
    'common.more': 'More',
    'common.search': 'Search',
    'common.all': 'All',
    'common.income': 'Income',
    'common.expense': 'Expenses',
    'common.deleting': 'Deleting',
    'common.loading': 'Loading...',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.create': 'Create',
    'common.deposit': 'Deposit',
    'common.progress': 'Progress',
    'common.pending': 'Pending',
    'common.paid': 'Paid',
    'common.overdue': 'Overdue',
    'common.entries': '{{count}} entries',
    'common.noData': 'No data available',

    'sidebar.dashboard': 'Dashboard',
    'sidebar.accounts': 'Accounts',
    'sidebar.budgets': 'Budgets',
    'sidebar.goals': 'Goals',
    'sidebar.invoices': 'Invoices',
    'sidebar.timeline': 'Timeline',
    'sidebar.fixed': 'Recurring',
    'sidebar.history': 'History',
    'sidebar.feedbacks': 'Feedbacks',
    'sidebar.admin': 'Admin Panel',
    'sidebar.settings': 'Settings',
    'sidebar.mobileDownload': 'Download Mobile Version',
    'sidebar.leaveFeedback': 'Leave Feedback',
    'sidebar.mobileSettings': 'Settings',

    'header.dashboard': 'Dashboard',
    'header.accounts': 'Accounts & Cards',
    'header.timeline': 'Timeline',
    'header.goals': 'Goals & Dreams',
    'header.budgets': 'Budgets',
    'header.invoices': 'Invoices',
    'header.fixed': 'Recurring',
    'header.feedbacks': 'Feedbacks (Admin)',
    'header.admin': 'Admin Panel',
    'header.history': 'History',
    'header.settings': 'Settings',
    'header.newTransaction': 'New Entry',
    'header.newTransactionMobile': '+ Entry',
    'header.newTransactionTitle': 'New Entry',

    'dashboard.available': 'Available (Month)',
    'dashboard.currentBalance': 'Current Balance',
    'dashboard.cardInvoice': 'Card Invoice',
    'dashboard.monthIncome': 'Income (Month)',
    'dashboard.monthExpense': 'Expenses (Month)',
    'dashboard.smartInsights': 'Smart Insights',
    'dashboard.analyzeMonth': 'Analyze my Month',
    'dashboard.updateTips': 'Update Tips',
    'dashboard.insightsPrompt': 'Ask our AI to analyze your expenses this month and get personalized tips.',
    'dashboard.monthlyPerformance': 'Monthly Performance',
    'dashboard.cashFlow': 'Consolidated cash flow',
    'dashboard.welcome': 'Welcome to Finanza!',
    'dashboard.welcomeDesc': 'To start organizing your finances, first record where your money is kept.',
    'dashboard.addAccount': 'Go to "Accounts & Cards" in the menu',
    'dashboard.noEntries': 'No entries this month',
    'dashboard.noEntriesDesc': 'Start organizing your finances by recording your first transaction.',
    'dashboard.startEntry': 'Start with the "New Entry" button',
    'dashboard.fixedPending': 'Pending Fixed',
    'dashboard.allPaid': 'All Paid!',
    'dashboard.noPendingFixed': 'No pending fixed bills.',
    'dashboard.topExpenses': 'Top Expenses',
    'dashboard.insufficientData': 'Not enough data.',
    'dashboard.compromise': 'Commitment Rate',
    'dashboard.fixedRatioDesc': 'of your monthly income is committed to fixed expenses.',
    'dashboard.fixedCost': 'Fixed Costs',
    'dashboard.free': 'Free',
    'dashboard.fixedLabel': 'Fixed: {{value}}',
    'dashboard.ruleTitle': '50/30/20 Rule',
    'dashboard.financialHealth': 'Financial Health',
    'dashboard.needs': 'Needs (50%)',
    'dashboard.wants': 'Wants (30%)',
    'dashboard.savings': 'Savings (20%)',
    'dashboard.other': 'Other',
    'dashboard.uncategorized': 'Uncategorized in rule',
    'dashboard.resourceAllocation': 'Resource Allocation',
    'dashboard.expenses': 'Expenses',
    'dashboard.noCategoryData': 'No categorization data',
    'dashboard.pendingInvoices': 'Pending Invoices',
    'dashboard.creditCard': 'Credit Card',
    'dashboard.due': 'Due {{date}}',
    'dashboard.total': 'Total: {{value}}',
    'dashboard.paid': 'Paid: {{value}}',
    'dashboard.suggestion': 'Suggestion: {{value}}',
    'dashboard.incomes': 'Income',
    'dashboard.revenues': 'Income',
    'dashboard.needsTooltip': 'Essential expenses like Rent, Food, Utilities, and Health. Suggested limit: 50%.',
    'dashboard.wantsTooltip': 'Leisure, Hobbies, Subscriptions, Restaurants, and non-essential purchases. Suggested limit: 30%.',
    'dashboard.savingsTooltip': 'Investments, Emergency Fund, Retirement, and Debt Payment. Suggested minimum: 20%.',
    'dashboard.uncategorizedTooltip': 'Expenses in categories not classified in the 50/30/20 rule (custom categories).',

    'history.title': 'Detailed History',
    'history.subtitle': 'Transactions',
    'history.noTransactions': 'No transactions',
    'history.noTransactionsDesc': 'Transactions will appear here as you add them.',
    'history.loadError': 'Error loading history',
    'history.loadErrorDesc': 'We could not load your transactions right now. Please try again shortly.',
    'history.filterAll': 'All',
    'history.filterIncome': 'Income',
    'history.filterExpense': 'Expenses',
    'history.other': 'Other',
    'history.search': 'Search transactions...',
    'history.consolidated': 'Consolidated History',
    'history.smartFilters': 'Smart Filters',
    'history.columnItem': 'Item',
    'history.columnCategory': 'Category',
    'history.columnDate': 'Date',
    'history.columnAmount': 'Amount',
    'history.columnManage': 'Manage',

    'timeline.title': 'Financial Path',
    'timeline.subtitle': 'Temporal Journey',
    'timeline.desc': 'Your detailed story day by day',
    'timeline.noData': 'No transactions found',
    'timeline.loading': 'Loading timeline...',
    'timeline.loadError': 'Error loading timeline',
    'timeline.loadErrorDesc': 'We could not load your transactions right now. Please try again shortly.',

    'goals.title': 'Goals & Dreams',
    'goals.newGoal': 'New Goal',
    'goals.editGoal': 'Edit Goal',
    'goals.goalTitle': 'Title',
    'goals.targetAmount': 'Target Amount',
    'goals.currentAmount': 'Current Amount',
    'goals.deadline': 'Deadline',
    'goals.progress': 'Progress: {{percent}}%',
    'goals.remaining': '{{value}} remaining',
    'goals.noGoals': 'Create your first goal',
    'goals.noGoalsDesc': 'Set financial goals to stay focused and track your progress.',
    'goals.deposit': 'Deposit',
    'goals.depositAmount': 'Deposit amount',
    'goals.depositSuccess': 'Deposit successful!',
    'goals.depositError': 'Error making deposit',
    'goals.saved': 'Saved!',
    'goals.notFound': 'Goal not found',
    'goals.deleteConfirm': 'Are you sure you want to delete this goal?',
    'goals.deleteSuccess': 'Goal deleted successfully!',
    'goals.deleteError': 'Error deleting goal',
    'goals.saving': 'Saving...',
    'goals.saveSuccess': 'Goal saved successfully!',
    'goals.saveError': 'Error saving goal',
    'goals.income': 'Income',
    'goals.amount': 'Amount',
    'goals.daysLeft': '{{days}} days left',

    'budgets.title': 'Budgets',
    'budgets.planning': 'Planning',
    'budgets.noBudgets': 'No budgets created',
    'budgets.noBudgetsDesc': 'Create budgets by category to control your spending.',
    'budgets.newBudget': 'New Budget',
    'budgets.editBudget': 'Edit Budget',
    'budgets.category': 'Category',
    'budgets.amount': 'Limit Amount',
    'budgets.spent': 'Spent',
    'budgets.remaining': 'Remaining',
    'budgets.overBudget': 'Over Budget!',
    'budgets.withinBudget': 'Within Budget',
    'budgets.freeLimit': 'Free plan allows 3 budgets. Upgrade to Premium to create more.',
    'budgets.freeLimitTitle': 'Free plan limit',
    'budgets.createMore': 'Upgrade to create more',
    'budgets.viewPremium': 'View Premium',
    'budgets.loading': 'Loading budgets...',
    'budgets.loadError': 'Error loading budgets',
    'budgets.fillAllFields': 'Fill in all fields',
    'budgets.invalidAmount': 'Invalid amount',
    'budgets.updateSuccess': 'Budget updated successfully!',
    'budgets.saving': 'Saving...',
    'budgets.saveSuccess': 'Budget saved successfully!',
    'budgets.saveError': 'Error saving budget',
    'budgets.deleteSuccess': 'Budget deleted successfully!',
    'budgets.deleteError': 'Error deleting budget',
    'budgets.deleteConfirm': 'Are you sure you want to delete this budget?',
    'budgets.deleteConfirmWithCategory': 'Are you sure you want to delete the budget for {{category}}?',
    'budgets.deleteBudget': 'Delete Budget',
    'budgets.readOnlyMode': 'Read-only mode',
    'budgets.used': 'used',
    'budgets.planYourExpenses': 'Plan your spending',
    'budgets.selectCategory': 'Select a category...',
    'budgets.incomeGroup': 'Income (Earnings)',
    'budgets.needsGroup': 'Needs (Essential)',
    'budgets.wantsGroup': 'Wants (Lifestyle)',
    'budgets.goalsGroup': 'Goals (Debt payoff and savings)',
    'budgets.desiredMonthlyLimit': 'Desired Monthly Limit',
    'budgets.updateBudget': 'Update Budget',
    'budgets.saveBudget': 'Save Budget',

    'recurring.title': 'Recurring',
    'recurring.subtitle': 'Monthly fixed entries',
    'recurring.noRecurring': 'No recurring entries',
    'recurring.noRecurringDesc': 'Set up fixed bills like rent, subscriptions and salaries.',
    'recurring.newRecurring': 'New Recurring',
    'recurring.editRecurring': 'Edit Recurring',
    'recurring.description': 'Description',
    'recurring.amount': 'Amount',
    'recurring.type': 'Type',
    'recurring.dueDay': 'Due Day',
    'recurring.category': 'Category',
    'recurring.account': 'Account',
    'recurring.monthlyWeight': 'Monthly Weight',
    'recurring.totalFixed': 'Total Fixed',
    'recurring.missingTotal': 'Missing Total',
    'recurring.loadError': 'Error loading recurring',
    'recurring.saveSuccess': 'Recurring saved successfully!',
    'recurring.saveError': 'Error saving recurring',
    'recurring.deleteSuccess': 'Recurring deleted successfully!',
    'recurring.deleteError': 'Error deleting recurring',
    'recurring.deleteConfirm': 'Are you sure you want to delete this recurring entry?',
    'recurring.typeIncome': 'Income',
    'recurring.typeExpense': 'Expense',
    'recurring.saving': 'Saving...',

    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your personal data and plan.',
    'settings.preferences': 'Preferences',
    'settings.preferences.helper': 'Currency defines the symbol/amount. Language defines texts plus date and number formatting.',
    'settings.currency': 'Currency',
    'settings.language': 'Language',
    'settings.language.pt': 'Portuguese (Brazil)',
    'settings.language.en': 'English (US)',
    'settings.locale': 'Locale',
    'settings.locale.ptBR': 'Portuguese (Brazil)',
    'settings.locale.enUS': 'English (US)',
    'settings.locale.ptPT': 'Portuguese (Portugal)',
    'settings.locale.deDE': 'German (Germany)',
    'settings.locale.enIE': 'English (Ireland)',
    'settings.preferencesSaved': 'Preferences saved successfully!',
    'settings.preferencesError': 'Error saving preferences',
    'settings.displayName': 'Display Name',
    'settings.namePlaceholder': 'Your name',
    'settings.email': 'Email',
    'settings.newEmail': 'New email',
    'settings.confirmPasswordCurrent': 'Confirm your password',
    'settings.password': 'Password',
    'settings.passwordButton': 'Change access password',
    'settings.currentPassword': 'Current password',
    'settings.newPassword': 'New password (min. 8 characters, letters and numbers)',
    'settings.confirmPassword': 'Confirm new password',
    'settings.passwordMismatch': 'Passwords do not match',
    'settings.plan': 'Current Plan',
    'settings.plan.free': 'Free',
    'settings.plan.premium': 'Premium',
    'settings.plan.freeDesc': '1 AI request/day, 1 account, 1 card, 3 budgets, 3 goals',
    'settings.plan.premiumDesc': 'Unlimited AI, unlimited accounts and budgets',
    'settings.confirmEmailChange': 'Confirm Change',
    'settings.changePassword': 'Change Password',
    'settings.success.name': 'Name updated successfully!',
    'settings.success.password': 'Password changed successfully!',
    'settings.success.email': 'Email changed! Check your new address.',
    'settings.error.name': 'Error changing name',
    'settings.error.password': 'Error changing password',
    'settings.error.email': 'Error changing email',
    'settings.error.passwordLength': 'The new password must be at least 8 characters long, including letters and numbers',
    'settings.upgradePremium': 'Upgrade to Premium',
    'settings.deleteAccount': 'Delete Account',
    'settings.deleteAccountDesc': 'Irreversible action — all data will be lost',
    'settings.delete': 'Delete',
    'settings.deleteWarning': '⚠️ This action is irreversible!',
    'settings.deleteItems': 'All your transactions will be deleted\nBank accounts, cards and balances will be erased\nGoals, budgets and custom categories will be lost\nYour premium plan will be canceled without refund\nData cannot be recovered afterward',
    'settings.deletePasswordPlaceholder': 'Enter your password to confirm',
    'settings.deleteConfirmLabel': 'Type DELETE to confirm',
    'settings.deleteConfirmPlaceholder': 'DELETE',
    'settings.deletePermanently': 'Delete Permanently',
    'settings.deleteError': 'Error deleting account',
    'settings.maintenance': 'Maintenance & Data',
    'settings.exportTransactions': 'Export Transactions',
    'settings.exportCSV': 'CSV Backup',
    'settings.exportPersonalData': 'Export Personal Data',
    'settings.exportLGPD': 'LGPD — Complete portability (JSON)',
    'settings.exportSuccess': 'Personal data exported successfully (LGPD — portability)',
    'settings.exportError': 'Error exporting personal data',
    'settings.logout': 'Logout',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

function interpolate(template: string, params?: TranslationParams): string {
  if (!params) return template;
  return Object.entries(params).reduce(
    (acc, [key, value]) => acc.replaceAll(`{{${key}}}`, String(value)),
    template,
  );
}

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<AppLanguage>('pt-BR');
  const [locale, setLocaleState] = useState<AppLocale>('pt-BR');
  const [localeCustomized, setLocaleCustomized] = useState(false);

  useEffect(() => {
    const storedLanguage = localStorage.getItem(STORAGE_KEY);
    if (storedLanguage === 'pt-BR' || storedLanguage === 'en') {
      setLanguageState(storedLanguage);
    }

    const storedLocale = localStorage.getItem(LOCALE_STORAGE_KEY);
    if (storedLocale === 'pt-BR' || storedLocale === 'en-US' || storedLocale === 'pt-PT' || storedLocale === 'de-DE' || storedLocale === 'en-IE') {
      setLocaleState(storedLocale);
      setLocaleCustomized(true);
    } else if (storedLanguage === 'en') {
      setLocaleState('en-US');
      setLocaleCustomized(false);
    } else {
      setLocaleState('pt-BR');
      setLocaleCustomized(false);
    }
  }, []);

  const setLanguage = (newLanguage: AppLanguage) => {
    setLanguageState(newLanguage);
    localStorage.setItem(STORAGE_KEY, newLanguage);

    if (!localeCustomized) {
      const defaultLocale: AppLocale = newLanguage === 'en' ? 'en-US' : 'pt-BR';
      setLocaleState(defaultLocale);
      localStorage.setItem(LOCALE_STORAGE_KEY, defaultLocale);
    }
  };

  const setLocale = (newLocale: AppLocale) => {
    setLocaleState(newLocale);
    setLocaleCustomized(true);
    localStorage.setItem(LOCALE_STORAGE_KEY, newLocale);
  };

  const t = (key: string, params?: TranslationParams) => {
    const fallback = translations['pt-BR'][key] ?? key;
    const translated = translations[language][key] ?? fallback;
    return interpolate(translated, params);
  };

  const value = useMemo(() => ({ language, setLanguage, locale, setLocale, t }), [language, locale]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
